From ubuntu:20.04
LABEL description = "React Native"

RUN apt-get update
RUN apt-get upgrade -y

Run apt-get install -y nodejs
RUN apt-get install -y npm
RUN apt-get install -y default-jdk
RUN npm install -g react-native-cli
RUN npm install expo-cli --global

